# Generated by Django 3.0.4 on 2020-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value_str', models.CharField(blank=True, max_length=200)),
                ('value_int', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('competitor_id', models.IntegerField()),
                ('competitor_code', models.CharField(max_length=200, unique=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('task_start', models.DateTimeField()),
            ],
        ),
    ]
