# Generated by Django 3.0.4 on 2020-03-30 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Competitor',
        ),
    ]
