# Generated by Django 3.0.4 on 2020-03-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0002_auto_20200330_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.IntegerField()),
                ('enabled', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
