# Generated by Django 3.0.4 on 2020-03-30 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='safecracker.Competitor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='safecracker.Task')),
            ],
        ),
    ]
