# Generated by Django 3.0.4 on 2020-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0005_task_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_dec',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
