# Generated by Django 3.0.4 on 2020-04-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0008_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='title',
        ),
    ]
