# Generated by Django 3.0.4 on 2020-04-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safecracker', '0009_remove_attachment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='safecracker.Competitor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='safecracker.Task')),
            ],
        ),
    ]
